# Generated by Django 3.2.8 on 2021-10-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20211029_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ice_2',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_2',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='work',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='secondary',
            field=models.TextField(null=True),
        ),
    ]
